query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query projectQuery($relativePath: String!) {
  ...LayoutQueryFragment
  project(relativePath: $relativePath) {
    ...ProjectParts
  }
}
